# Generated by Django 3.0.5 on 2020-04-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liner_title', models.TextField(max_length=1000)),
                ('liner_covered_title', models.TextField(max_length=1000)),
                ('square_covered_title', models.TextField(max_length=1000)),
                ('lifeless_title', models.TextField(max_length=1000)),
                ('quarantine_title', models.TextField(max_length=1000)),
                ('down1_title', models.TextField(max_length=1000)),
                ('custom_title', models.TextField(max_length=1000)),
                ('custom_down_title', models.TextField(max_length=1000)),
                ('activity_title', models.TextField(max_length=1000)),
                ('resources', models.TextField(max_length=1000)),
            ],
        ),
    ]
