# Generated by Django 3.0.5 on 2020-04-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='activity_title',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='information',
            name='custom_down_title',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='information',
            name='custom_title',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='information',
            name='down1_title',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='information',
            name='lifeless_title',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='information',
            name='liner_covered_title',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='information',
            name='liner_title',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='information',
            name='quarantine_title',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='information',
            name='resources',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='information',
            name='square_covered_title',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
